# Generated by Django 5.0.6 on 2024-06-10 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=75)),
                ('apellidoPat', models.CharField(max_length=50)),
                ('apellidoMat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
                ('titulo', models.CharField()),
                ('autor', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(default=0)),
                ('disponibilidad', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fechaCreada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoReporte', models.CharField(max_length=20)),
                ('contenido', models.TextField()),
                ('fechaCreada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=75)),
                ('apellidoPat', models.CharField(max_length=50)),
                ('apellidoMat', models.CharField(max_length=50)),
                ('nombreUsuario', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=8)),
                ('tipoUsuario', models.CharField(max_length=1)),
                ('fechaCreada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaReserva', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('libroReserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BibliotecaApp.libro')),
                ('usuarioReserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BibliotecaApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPrestamo', models.DateField()),
                ('fechaDevolucion', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('libroPrestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BibliotecaApp.libro')),
                ('usuarioPrestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BibliotecaApp.usuario')),
            ],
        ),
    ]
